//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContratacionEmpleados.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bd_PruebasEntities : DbContext
    {
        public bd_PruebasEntities()
            : base("name=bd_PruebasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<TipoContrato> TipoContrato { get; set; }
        public virtual DbSet<VW_Contrato> VW_Contrato { get; set; }
    
        public virtual ObjectResult<RP_Contrato_Filtro_Fecha_Result> RP_Contrato_Filtro_Fecha(Nullable<System.DateTime> fechaI, Nullable<System.DateTime> fechaF)
        {
            var fechaIParameter = fechaI.HasValue ?
                new ObjectParameter("FechaI", fechaI) :
                new ObjectParameter("FechaI", typeof(System.DateTime));
    
            var fechaFParameter = fechaF.HasValue ?
                new ObjectParameter("FechaF", fechaF) :
                new ObjectParameter("FechaF", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RP_Contrato_Filtro_Fecha_Result>("RP_Contrato_Filtro_Fecha", fechaIParameter, fechaFParameter);
        }
    
        public virtual ObjectResult<RP_Salario_Calculado_Result> RP_Salario_Calculado(Nullable<int> idcontrato, Nullable<System.DateTime> fechaI, Nullable<System.DateTime> fechaF)
        {
            var idcontratoParameter = idcontrato.HasValue ?
                new ObjectParameter("Idcontrato", idcontrato) :
                new ObjectParameter("Idcontrato", typeof(int));
    
            var fechaIParameter = fechaI.HasValue ?
                new ObjectParameter("FechaI", fechaI) :
                new ObjectParameter("FechaI", typeof(System.DateTime));
    
            var fechaFParameter = fechaF.HasValue ?
                new ObjectParameter("FechaF", fechaF) :
                new ObjectParameter("FechaF", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RP_Salario_Calculado_Result>("RP_Salario_Calculado", idcontratoParameter, fechaIParameter, fechaFParameter);
        }
    }
}
