//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContratacionEmpleados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Contrato
    {
        public string Nombres { get; set; }
        public string Codigo { get; set; }
        public int IdContrato { get; set; }
        public Nullable<bool> EstadoFila { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public double Salario { get; set; }
        public string NombreArea { get; set; }
        public string NombreCargo { get; set; }
        public string NombreTipoContrato { get; set; }
    }
}
